/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AlertMessage: typeof import('./components/AlertMessage.vue')['default']
    ExportFileForm: typeof import('./components/ExportFileForm.vue')['default']
    InventoryTable: typeof import('./components/InventoryTable.vue')['default']
    LoginForm: typeof import('./components/LoginForm.vue')['default']
    QrTable: typeof import('./components/QrTable.vue')['default']
    RegisterForm: typeof import('./components/RegisterForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SuggestDialog: typeof import('./components/SuggestDialog.vue')['default']
    UpdateDialog: typeof import('./components/UpdateDialog.vue')['default']
    UserModTable: typeof import('./components/UserModTable.vue')['default']
  }
}
