/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/auth': RouteRecordInfo<'/auth', '/auth', Record<never, never>, Record<never, never>>,
    '/export-page': RouteRecordInfo<'/export-page', '/export-page', Record<never, never>, Record<never, never>>,
    '/item-page': RouteRecordInfo<'/item-page', '/item-page', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/production': RouteRecordInfo<'/production', '/production', Record<never, never>, Record<never, never>>,
    '/table-page': RouteRecordInfo<'/table-page', '/table-page', Record<never, never>, Record<never, never>>,
    '/useradd': RouteRecordInfo<'/useradd', '/useradd', Record<never, never>, Record<never, never>>,
    '/usermod': RouteRecordInfo<'/usermod', '/usermod', Record<never, never>, Record<never, never>>,
  }
}
